In [1]:
import pandas as pd
import numpy as np

In [2]:
data = []

In [3]:
LeftLow = 7
LeftHigh = 7.5

midLeftLow = 7.5
midLeftHigh = 8

midRightLow = 8
midRightHigh = 8.5

RightLow = 8.5 
RightHigh = 9

for i in range(1,21):
    
    
    #AM = 0
    #PM =1
    if i%2 == 0:
        # Time : 3,9
        data.append([i,3,0,round(np.random.uniform(LeftLow,LeftHigh),2)])
        data.append([i,9,0,round(np.random.uniform(RightLow,RightHigh),2)])
        data.append([i,9,1,round(np.random.uniform(midRightLow,midRightHigh),2)])
        data.append([i,3,1,round(np.random.uniform(midLeftLow,midLeftHigh),2)])
        if i<6:
            LeftLow += 0.5
            LeftHigh += 0.5
            RightLow += 0.5
            RightHigh += 0.5
            midLeftLow += 0.5
            midLeftHigh += 0.5
            midRightLow += 0.5
            midRightHigh += 0.5



    else:
        #Time : 6,12
        data.append([i,6,0,round(np.random.uniform(LeftLow,LeftHigh),2)])
        data.append([i,12,0,round(np.random.uniform(midLeftLow,midLeftHigh),2)])
        data.append([i,12,1,round(np.random.uniform(midRightLow,midRightHigh),2)])
        data.append([i,6,1,round(np.random.uniform(RightLow,RightHigh),2)])

In [4]:
len(data)

80

In [5]:
dataPanda = pd.DataFrame(data , columns=['numberOfCars','time','dayNight','Price'])

In [6]:
dataPanda

    numberOfCars  time  dayNight  Price
0              1     6         0   7.11
1              1    12         0   7.96
2              1    12         1   8.13
3              1     6         1   8.79
4              2     3         0   7.09
5              2     9         0   8.77
6              2     9         1   8.39
7              2     3         1   7.59
8              3     6         0   7.68
9              3    12         0   8.43
10             3    12         1   8.89
11             3     6         1   9.42
12             4     3         0   7.87
13             4     9         0   9.36
14             4     9         1   8.62
15             4     3         1   8.35
16             5     6         0   8.40
17             5    12         0   8.83
18             5    12         1   9.00
19             5     6         1   9.62
20             6     3         0   8.01
21             6     9         0   9.84
22             6     9         1   9.13
23             6     3         1   8.96
24             7     6         0   8.37
25             7    12         0   8.84
26             7    12         1   9.18
27             7     6         1   9.64
28             8     3         0   8.31
29             8     9         0   9.88
..           ...   ...       ...    ...
50            13    12         1   9.42
51            13     6         1   9.83
52            14     3         0   8.03
53            14     9         0   9.72
54            14     9         1   9.17
55            14     3         1   8.53
56            15     6         0   8.41
57            15    12         0   8.76
58            15    12         1   9.07
59            15     6         1   9.64
60            16     3         0   8.44
61            16     9         0   9.61
62            16     9         1   9.34
63            16     3         1   8.69
64            17     6         0   8.18
65            17    12         0   8.64
66            17    12         1   9.21
67            17     6         1   9.93
68            18     3         0   8.14
69            18     9         0   9.61
70            18     9         1   9.22
71            18     3         1   8.51
72            19     6         0   8.45
73            19    12         0   8.98
74            19    12         1   9.14
75            19     6         1   9.99
76            20     3         0   8.38
77            20     9         0   9.83
78            20     9         1   9.18
79            20     3         1   8.51

[80 rows x 4 columns]

In [7]:
dataPanda.to_csv('Data')

# Cheers!